[project]
name = "kokorolm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kokoro>=0.9.4",
    "librosa>=0.11.0",
    "numpy>=2.3.5",
    "openai>=2.8.1",
    "soundfile>=0.13.1",
]
